---
name: Graphics-Colourset
version: 0.01
author:
  - Kathryn Andersen
abstract: create sets of colours.
license: perl
requires:
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  Graphics::ColorObject: 0.4
  Pod::Usage: 0
build_requires:
  Test::More: 0
provides:
  Graphics::Colourset:
    file: lib/Graphics/Colourset.pm
    version: 0.01
generated_by: Module::Build version 0.2611
